version: '3.7'

services:

  augmented-reality:
    image: ruhyadi/augmented-reality:latest
    stdin_open: true
    tty: true
    volumes:
      - ./:/ar
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1